In [ ]:
import pandas as pd
df1SE = pd.DataFrame({
    'StudentID': [101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121],
    'ScoreSE': [65, 72, 58, 81, 69, 75, 88, 54, 79, 91, 67]
})

df2SE = pd.DataFrame({
    'StudentID': [102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122],
    'ScoreSE': [73, 84, 62, 77, 85, 68, 90, 74, 59, 83, 71]
})

df1ML = pd.DataFrame({
    'StudentID': [101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121],
    'ScoreML': [70, 80, 66, 89, 74, 92, 78, 63, 81, 87, 72]
})

df2ML = pd.DataFrame({
    'StudentID': [102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122],
    'ScoreML': [76, 85, 69, 82, 90, 73, 88, 65, 79, 91, 75]
})

In [ ]:
# Concatenation

dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

In [ ]:
# Column-wise Concatenation

df = pd.concat([dfML, dfSE], axis=1)
df

    StudentID  ScoreML  StudentID  ScoreSE
0         101       70        101       65
1         103       80        103       72
2         105       66        105       58
3         107       89        107       81
4         109       74        109       69
5         111       92        111       75
6         113       78        113       88
7         115       63        115       54
8         117       81        117       79
9         119       87        119       91
10        121       72        121       67
11        102       76        102       73
12        104       85        104       84
13        106       69        106       62
14        108       82        108       77
15        110       90        110       85
16        112       73        112       68
17        114       88        114       90
18        116       65        116       74
19        118       79        118       59
20        120       91        120       83
21        122       75        122       71

In [ ]:
# Inner Join

df = dfSE.merge(dfML, how='inner')
df

    StudentID  ScoreSE  ScoreML
0         101       65       70
1         103       72       80
2         105       58       66
3         107       81       89
4         109       69       74
5         111       75       92
6         113       88       78
7         115       54       63
8         117       79       81
9         119       91       87
10        121       67       72
11        102       73       76
12        104       84       85
13        106       62       69
14        108       77       82
15        110       85       90
16        112       68       73
17        114       90       88
18        116       74       65
19        118       59       79
20        120       83       91
21        122       71       75

In [ ]:
# Inner Join

df = dfSE.merge(dfML, how='inner')
df

    StudentID  ScoreSE  ScoreML
0         101       65       70
1         103       72       80
2         105       58       66
3         107       81       89
4         109       69       74
5         111       75       92
6         113       88       78
7         115       54       63
8         117       79       81
9         119       91       87
10        121       67       72
11        102       73       76
12        104       84       85
13        106       62       69
14        108       77       82
15        110       85       90
16        112       68       73
17        114       90       88
18        116       74       65
19        118       59       79
20        120       83       91
21        122       71       75

In [ ]:
# Right Join

df = dfSE.merge(dfML, how='right')
df

    StudentID  ScoreSE  ScoreML
0         101       65       70
1         103       72       80
2         105       58       66
3         107       81       89
4         109       69       74
5         111       75       92
6         113       88       78
7         115       54       63
8         117       79       81
9         119       91       87
10        121       67       72
11        102       73       76
12        104       84       85
13        106       62       69
14        108       77       82
15        110       85       90
16        112       68       73
17        114       90       88
18        116       74       65
19        118       59       79
20        120       83       91
21        122       71       75

In [ ]:
# Read CSV

df = pd.read_csv("1000 Sales Records.csv")
df.head(10)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45
5,Europe,Armenia,Cereal,Online,H,11/24/2014,683458888,12/28/2014,9528,205.70,117.11,1959909.60,1115824.08,844085.52
6,Sub-Saharan Africa,Eritrea,Cereal,Online,H,3/4/2015,679414975,4/17/2015,2844,205.70,117.11,585010.80,333060.84,251949.96
7,Europe,Montenegro,Clothes,Offline,M,5/17/2012,208630645,6/28/2012,7299,109.28,35.84,797634.72,261596.16,536038.56
8,Central America and the Caribbean,Jamaica,Vegetables,Online,H,1/29/2015,266467225,3/7/2015,2428,154.06,90.93,374057.68,220778.04,153279.64
9,Australia and Oceania,Fiji,Vegetables,Offline,H,12/24/2013,118598544,1/19/2014,4800,154.06,90.93,739488.00,436464.00,303024.00

In [ ]:
# New Column

df["Profit Per Unit"] = df["Unit Price"] - df["Unit Cost"]
df.head(10)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Profit Per Unit
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02,173.87
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34,63.13
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62,95.86
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98,88.59
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45,2.41
5,Europe,Armenia,Cereal,Online,H,11/24/2014,683458888,12/28/2014,9528,205.70,117.11,1959909.60,1115824.08,844085.52,88.59
6,Sub-Saharan Africa,Eritrea,Cereal,Online,H,3/4/2015,679414975,4/17/2015,2844,205.70,117.11,585010.80,333060.84,251949.96,88.59
7,Europe,Montenegro,Clothes,Offline,M,5/17/2012,208630645,6/28/2012,7299,109.28,35.84,797634.72,261596.16,536038.56,73.44
8,Central America and the Caribbean,Jamaica,Vegetables,Online,H,1/29/2015,266467225,3/7/2015,2428,154.06,90.93,374057.68,220778.04,153279.64,63.13
9,Australia and Oceania,Fiji,Vegetables,Offline,H,12/24/2013,118598544,1/19/2014,4800,154.06,90.93,739488.00,436464.00,303024.00,63.13

In [ ]:
# Value Counts

df["Region"].value_counts()

Region
Europe                               267
Sub-Saharan Africa                   262
Middle East and North Africa         138
Asia                                 136
Central America and the Caribbean     99
Australia and Oceania                 79
North America                         19
Name: count, dtype: int64

In [ ]:
  # Descriptive Statistics

df.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Profit Per Unit
count,1.000000e+03,1000.000000,1000.00000,1000.000000,1.000000e+03,1.000000e+03,1.000000e+03,1000.000000
mean,5.496813e+08,5053.988000,262.10684,184.965110,1.327322e+06,9.361192e+05,3.912026e+05,77.141730
std,2.571334e+08,2901.375317,216.02106,175.289311,1.486515e+06,1.162571e+06,3.836402e+05,51.610854
min,1.029280e+08,13.000000,9.33000,6.920000,2.043250e+03,1.416750e+03,5.326100e+02,2.410000
25%,3.280740e+08,2420.250000,81.73000,56.670000,2.811919e+05,1.649319e+05,9.837612e+04,25.060000
50%,5.566097e+08,5184.000000,154.06000,97.440000,7.549392e+05,4.647261e+05,2.772260e+05,63.130000
75%,7.696945e+08,7536.750000,421.89000,263.330000,1.733503e+06,1.141750e+06,5.484568e+05,95.860000
max,9.955298e+08,9998.000000,668.27000,524.960000,6.617210e+06,5.204978e+06,1.726181e+06,173.870000