In [14]:
import numpy as np
import pandas as pd

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, IterativeImputer

student_data = pd.DataFrame({
    "Marks": [82, np.nan, 74, 91, 67, np.nan],
    "Study_Hours": [5, 7, np.nan, 8, 4, 6],
    "Section": ["A", "B", np.nan, "A", "C", "B"]
})

print("Original Data")
student_data

Original Data

   Marks  Study_Hours Section
0   82.0          5.0       A
1    NaN          7.0       B
2   74.0          NaN     NaN
3   91.0          8.0       A
4   67.0          4.0       C
5    NaN          6.0       B

In [15]:
mean_fill = SimpleImputer(strategy="mean")

student_data["Marks_Mean"] = mean_fill.fit_transform(student_data[["Marks"]])

print("After Mean Imputation")
student_data

After Mean Imputation

   Marks  Study_Hours Section  Marks_Mean
0   82.0          5.0       A        82.0
1    NaN          7.0       B        78.5
2   74.0          NaN     NaN        74.0
3   91.0          8.0       A        91.0
4   67.0          4.0       C        67.0
5    NaN          6.0       B        78.5

In [16]:
median_fill = SimpleImputer(strategy="median")

student_data["Hours_Median"] = median_fill.fit_transform(student_data[["Study_Hours"]])

print("After Median Imputation")
student_data

After Median Imputation

   Marks  Study_Hours Section  Marks_Mean  Hours_Median
0   82.0          5.0       A        82.0           5.0
1    NaN          7.0       B        78.5           7.0
2   74.0          NaN     NaN        74.0           6.0
3   91.0          8.0       A        91.0           8.0
4   67.0          4.0       C        67.0           4.0
5    NaN          6.0       B        78.5           6.0

In [17]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

df = pd.DataFrame(
    {
        "Height": [165, np.nan, 172, 180, 168],
        "Weight": [60, 72, np.nan, 85, 65],
        "Department": ["IT", "CSE", "IT", np.nan, "ECE"],
    }
)

mode_imputer = SimpleImputer(strategy="most_frequent")
df["Department_Mode"] = mode_imputer.fit_transform(df[["Department"]]).ravel()

print(df)

   Height  Weight Department Department_Mode
0   165.0    60.0         IT              IT
1     NaN    72.0        CSE             CSE
2   172.0     NaN         IT              IT
3   180.0    85.0        NaN              IT
4   168.0    65.0        ECE             ECE

In [18]:
numeric_cols = ["Marks", "Study_Hours"]

mice = IterativeImputer(
    max_iter=10,
    random_state=10
)

temp = student_data[numeric_cols].copy()

temp.iloc[:, :] = mice.fit_transform(temp)

student_data["Marks_MICE"] = temp["Marks"]
student_data["Hours_MICE"] = temp["Study_Hours"]

print("After MICE Imputation")
student_data

After MICE Imputation

,Marks,Study_Hours,Section,Marks_Mean,Hours_Median,Marks_MICE,Hours_MICE
0,82.0,5.0,A,82.0,5.0,82.000000,5.000000
1,NaN,7.0,B,78.5,7.0,86.301692,7.000000
2,74.0,NaN,NaN,74.0,6.0,74.000000,4.845773
3,91.0,8.0,A,91.0,8.0,91.000000,8.000000
4,67.0,4.0,C,67.0,4.0,67.000000,4.000000
5,NaN,6.0,B,78.5,6.0,81.230906,6.000000